package com.dq.arq.sme.domain;
// default package
// Generated Nov 28, 2016 12:33:13 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Ad generated by hbm2java
 */
@Entity
@Table(name = "ad", catalog = "arq_sme")
public class AdDo implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public enum Status{
		Enabled,Paused,Disabled
	}
	private Integer id;
	private AdgroupDo adgroupDo;
	private Long apiId;
	private Long adgroupApiId;
	private Status status;	//1 - ENABLED, 2 - PAUSED, 3 - DISABLED
	private String businessName;
	private String phoneNumber;
	private String descriptionLine1;
	private String descriptionLine2;
	private String displayUrl;
	private String verificationUrl;
	private String createdBy;
	private Date createdOn;
	
	//Date Strings added to store dates starts
			private String createdOnString;
			
			@Transient
			public String getCreatedOnString() {
				return createdOnString;
			}
			public void setCreatedOnString(String createdOnString) {
				this.createdOnString = createdOnString;
			}

			//Date Strings added to store dates ends
	
	private String updatedBy;
	private Date updatedOn;

	public AdDo() {
	}

	public AdDo(AdgroupDo adgroupDo, String createdBy, Date createdOn) {
		this.adgroupDo = adgroupDo;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}

	public AdDo(AdgroupDo adgroupDo, Long apiId, Long adgroupApiId,
			String status, String businessName, String phoneNumber,
			String descriptionLine1, String descriptionLine2,
			String displayUrl, String verificationUrl, String createdBy,
			Date createdOn, String updatedBy, Date updatedOn) {
		this.adgroupDo = adgroupDo;
		this.apiId = apiId;
		this.adgroupApiId = adgroupApiId;
		this.status = Status.valueOf(status);
		this.businessName = businessName;
		this.phoneNumber = phoneNumber;
		this.descriptionLine1 = descriptionLine1;
		this.descriptionLine2 = descriptionLine2;
		this.displayUrl = displayUrl;
		this.verificationUrl = verificationUrl;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adgroup_id", nullable = false)
	public AdgroupDo getAdgroupDo() {
		return this.adgroupDo;
	}

	public void setAdgroupDo(AdgroupDo adgroupDo) {
		this.adgroupDo = adgroupDo;
	}

	@Column(name = "api_id")
	public Long getApiId() {
		return this.apiId;
	}

	public void setApiId(Long apiId) {
		this.apiId = apiId;
	}

	@Column(name = "adgroup_api_id")
	public Long getAdgroupApiId() {
		return this.adgroupApiId;
	}

	public void setAdgroupApiId(Long adgroupApiId) {
		this.adgroupApiId = adgroupApiId;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status.name();
	}

	public void setStatus(String status) {
		this.status = Status.valueOf(status);
	}

	@Column(name = "business_name", length = 500)
	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	@Column(name = "phone_number", length = 100)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "description_line1", length = 4000)
	public String getDescriptionLine1() {
		return this.descriptionLine1;
	}

	public void setDescriptionLine1(String descriptionLine1) {
		this.descriptionLine1 = descriptionLine1;
	}

	@Column(name = "description_line2", length = 4000)
	public String getDescriptionLine2() {
		return this.descriptionLine2;
	}

	public void setDescriptionLine2(String descriptionLine2) {
		this.descriptionLine2 = descriptionLine2;
	}

	@Column(name = "display_url", length = 500)
	public String getDisplayUrl() {
		return this.displayUrl;
	}

	public void setDisplayUrl(String displayUrl) {
		this.displayUrl = displayUrl;
	}

	@Column(name = "verification_url", length = 500)
	public String getVerificationUrl() {
		return this.verificationUrl;
	}

	public void setVerificationUrl(String verificationUrl) {
		this.verificationUrl = verificationUrl;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 0)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
