package com.dq.arq.sme.domain;
// default package
// Generated Sep 20, 2016 5:09:12 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


/**
 * Campaign generated by hbm2java
 */
@Entity
@Table(name = "campaign")
public class CampaignDo implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public enum Status{
		Enabled,Paused,Removed,Unknown
	}
	private Integer id;
	private UserDo userDo;
	private Long apiId;
	private String name;
	/*status 1 is Enabled, 2 is Paused, 3 is Removed, 4 is unknown (Status of campaign status in adwords account) (4 is most probably because campaign wasn't 
	never created there successfully ever*/
		
	private Status status;
	private Integer biddingStrategyId;
	private String advertisingChannelType;
	private String locationInclude;
	private Integer locationIncludeCriteria;
	private String locationExclude;
	private Integer locationExcludeCriteria;
	private Double budgetAmount;
	private Long budgetId;
	private Date startDate;
	private Date endDate;
	
	//Date Strings added to store dates starts
		private String startDateString;
		private String endDateString;
		private String createdOnString;
		@Transient
		public String getStartDateString() {
			return startDateString;
		}
		public void setStartDateString(String startDateString) {
			this.startDateString = startDateString;
		}
		@Transient
		public String getEndDateString() {
			return endDateString;
		}
		public void setEndDateString(String endDateString) {
			this.endDateString = endDateString;
		}
		
		@Transient
		public String getCreatedOnString() {
			return createdOnString;
		}
		public void setCreatedOnString(String createdOnString) {
			this.createdOnString = createdOnString;
		}

		//Date Strings added to store dates ends
		
	

		//fields added for include location starts
		private List<Integer> includeLocationsList;
		private List<Integer> excludeLocationsList;
		
		@Transient
		public List<Integer> getIncludeLocationsList() {
			return includeLocationsList;
		}
		public void setIncludeLocationsList(List<Integer> includeLocationsList) {
			this.includeLocationsList = includeLocationsList;
		}
		
		@Transient
		public List<Integer> getExcludeLocationsList() {
			return excludeLocationsList;
		}
		public void setExcludeLocationsList(List<Integer> excludeLocationsList) {
			this.excludeLocationsList = excludeLocationsList;
		}
		

		//fields added for include location starts
	
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private List<AdgroupDo> adgroupDos = new ArrayList<AdgroupDo>(0);
	private List<CampaignPerformanceReportDo> campaignPerformanceReportDos = new ArrayList<CampaignPerformanceReportDo>(0);

	public CampaignDo() {
	}

	public CampaignDo(UserDo userDo, String createdBy, Date createdOn) {
		this.userDo = userDo;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
	}


	public CampaignDo(UserDo userDo,Long apiId, String name, String status,
			Integer biddingStrategyId, String advertisingChannelType,
			String locationInclude, Integer locationIncludeCriteria,
			String locationExclude, Integer locationExcludeCriteria,
			Double budgetAmount, Long budgetId, Date startDate, Date endDate,
			String createdBy, Date createdOn, String updatedBy, Date updatedOn,
			List<AdgroupDo> adgroupDos) {
		this.userDo = userDo;
		this.apiId = apiId;
		this.name = name;
		this.status = Status.valueOf(status);
		this.biddingStrategyId = biddingStrategyId;
		this.advertisingChannelType = advertisingChannelType;
		this.locationInclude = locationInclude;
		this.locationIncludeCriteria = locationIncludeCriteria;
		this.locationExclude = locationExclude;
		this.locationExcludeCriteria = locationExcludeCriteria;
		this.budgetAmount = budgetAmount;
		this.budgetId = budgetId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.adgroupDos = adgroupDos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDo getUserDo() {
		return this.userDo;
	}

	public void setUserDo(UserDo userDo) {
		this.userDo = userDo;
	}

	@Column(name = "api_id")
	public Long getApiId() {
		return this.apiId;
	}

	public void setApiId(Long apiId) {
		this.apiId = apiId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status.name();
	}

	public void setStatus(String status) {
		this.status = Status.valueOf(status);
	}

	@Column(name = "bidding_strategy_id")
	public Integer getBiddingStrategyId() {
		return this.biddingStrategyId;
	}

	public void setBiddingStrategyId(Integer biddingStrategyId) {
		this.biddingStrategyId = biddingStrategyId;
	}

	@Column(name = "advertising_channel_type", length = 50)
	public String getAdvertisingChannelType() {
		return this.advertisingChannelType;
	}

	public void setAdvertisingChannelType(String advertisingChannelType) {
		this.advertisingChannelType = advertisingChannelType;
	}

	@Column(name = "locationInclude", length = 4000)
	public String getLocationInclude() {
		return this.locationInclude;
	}

	public void setLocationInclude(String locationInclude) {
		this.locationInclude = locationInclude;
	}

	@Column(name = "locationInclude_Criteria")
	public Integer getLocationIncludeCriteria() {
		return this.locationIncludeCriteria;
	}

	public void setLocationIncludeCriteria(Integer locationIncludeCriteria) {
		this.locationIncludeCriteria = locationIncludeCriteria;
	}

	@Column(name = "locationExclude", length = 4000)
	public String getLocationExclude() {
		return this.locationExclude;
	}

	public void setLocationExclude(String locationExclude) {
		this.locationExclude = locationExclude;
	}

	@Column(name = "locationExclude_Criteria")
	public Integer getLocationExcludeCriteria() {
		return this.locationExcludeCriteria;
	}

	public void setLocationExcludeCriteria(Integer locationExcludeCriteria) {
		this.locationExcludeCriteria = locationExcludeCriteria;
	}

	@Column(name = "budget_amount", precision = 22, scale = 0)
	public Double getBudgetAmount() {
		return this.budgetAmount;
	}

	public void setBudgetAmount(Double budgetAmount) {
		this.budgetAmount = budgetAmount;
	}

	@Column(name = "budget_id")
	public Long getBudgetId() {
		return this.budgetId;
	}

	public void setBudgetId(Long budgetId) {
		this.budgetId = budgetId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 0)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campaignDo")
	public List<AdgroupDo> getAdgroupDos() {
		return this.adgroupDos;
	}

	public void setAdgroupDos(List<AdgroupDo> adgroupDos) {
		this.adgroupDos = adgroupDos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campaignDo")
	public List<CampaignPerformanceReportDo> getCampaignPerformanceReportDos() {
		return this.campaignPerformanceReportDos;
	}

	public void setCampaignPerformanceReportDos(
			List<CampaignPerformanceReportDo> campaignPerformanceReportDos) {
		this.campaignPerformanceReportDos = campaignPerformanceReportDos;
	}
	

}
