package com.dq.arq.sme.domain;
// default package
// Generated Dec 7, 2016 12:50:10 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CampaignPerformanceReport generated by hbm2java
 */
@Entity
@Table(name = "CAMPAIGN_PERFORMANCE_REPORT", catalog = "arq_sme")
public class CampaignPerformanceReportDo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private CampaignDo campaignDo;
	private Long clicks;
	private Long impressions;
	private Double cost;
	private Date date;

	public CampaignPerformanceReportDo() {
	}

	public CampaignPerformanceReportDo(CampaignDo campaignDo) {
		this.campaignDo = campaignDo;
	}

	public CampaignPerformanceReportDo(CampaignDo campaignDo, Long clicks,
			Long impressions, Double cost, Date date) {
		this.campaignDo = campaignDo;
		this.clicks = clicks;
		this.impressions = impressions;
		this.cost = cost;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false)
	public CampaignDo getCampaignDo() {
		return this.campaignDo;
	}

	public void setCampaignDo(CampaignDo campaignDo) {
		this.campaignDo = campaignDo;
	}

	@Column(name = "Clicks")
	public Long getClicks() {
		return this.clicks;
	}

	public void setClicks(Long clicks) {
		this.clicks = clicks;
	}

	@Column(name = "impressions")
	public Long getImpressions() {
		return this.impressions;
	}

	public void setImpressions(Long impressions) {
		this.impressions = impressions;
	}

	@Column(name = "cost")
	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
