package com.dq.arq.sme.domain;
// default package
// Generated Sep 20, 2016 5:09:12 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class CategoryDo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String primeCategory;
	private String category;

	public CategoryDo() {
	}

	public CategoryDo(int id) {
		this.id = id;
	}

	public CategoryDo(int id, String primeCategory, String category) {
		this.id = id;
		this.primeCategory = primeCategory;
		this.category = category;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "prime_category", length = 100)
	public String getPrimeCategory() {
		return this.primeCategory;
	}

	public void setPrimeCategory(String primeCategory) {
		this.primeCategory = primeCategory;
	}

	@Column(name = "category", length = 1000)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
