package com.dq.arq.sme.domain;
// default package
// Generated Sep 20, 2016 5:09:12 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "location")
public class LocationDo implements java.io.Serializable {

	private int criteriaId;
	private String name;
	private String canonicalName;
	private String parentId;
	private String countryCode;
	private String targetType;
	private String status;

	public LocationDo() {
	}

	public LocationDo(int criteriaId) {
		this.criteriaId = criteriaId;
	}

	public LocationDo(int criteriaId, String name, String canonicalName,
			String parentId, String countryCode, String targetType,
			String status) {
		this.criteriaId = criteriaId;
		this.name = name;
		this.canonicalName = canonicalName;
		this.parentId = parentId;
		this.countryCode = countryCode;
		this.targetType = targetType;
		this.status = status;
	}

	@Id
	@Column(name = "criteria_id", unique = true, nullable = false)
	public int getCriteriaId() {
		return this.criteriaId;
	}

	public void setCriteriaId(int criteriaId) {
		this.criteriaId = criteriaId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "canonical_name", length = 1000)
	public String getCanonicalName() {
		return this.canonicalName;
	}

	public void setCanonicalName(String canonicalName) {
		this.canonicalName = canonicalName;
	}

	@Column(name = "parent_id", length = 200)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "country_code", length = 10)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "target_type", length = 200)
	public String getTargetType() {
		return this.targetType;
	}

	public void setTargetType(String targetType) {
		this.targetType = targetType;
	}

	@Column(name = "status", length = 200)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
