package com.dq.arq.sme.domain;
// default package
// Generated Nov 21, 2016 12:36:34 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "productCategory", catalog = "arq_sme")
public class ProductCategoryDo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String category;

	public ProductCategoryDo() {
	}

	public ProductCategoryDo(int id) {
		this.id = id;
	}

	public ProductCategoryDo(int id, String category) {
		this.id = id;
		this.category = category;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "category", length = 4000)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
