package com.dq.arq.sme.domain;
// Generated Dec 19, 2016 2:56:58 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSessions generated by hbm2java
 */
@Entity
@Table(name = "user_session", catalog = "arq_sme")
public class UserSessionDo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String sessionId;
	private UserDo userDo;
	private Date loggedInTime;
	private Date loggedOutTime;
	private String ip;
	private Integer isLoggedIn;
	private String deviceDetails;

	public UserSessionDo() {
	}

	public UserSessionDo(UserDo userDo, Date loggedInTime) {
		this.userDo = userDo;
		this.loggedInTime = loggedInTime;
	}

	public UserSessionDo(String sessionId, UserDo userDo, Date loggedInTime, Date loggedOutTime,
			String ip, Integer isLoggedIn, String deviceDetails) {
		this.sessionId = sessionId;
		this.userDo = userDo;
		this.loggedInTime = loggedInTime;
		this.loggedOutTime = loggedOutTime;
		this.ip = ip;
		this.isLoggedIn = isLoggedIn;
		this.deviceDetails = deviceDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "session_id", length = 100)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDo getUserDo() {
		return this.userDo;
	}

	public void setUserDo(UserDo userDo) {
		this.userDo = userDo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logged_in_time", nullable = false, length = 0)
	public Date getLoggedInTime() {
		return this.loggedInTime;
	}

	public void setLoggedInTime(Date loggedInTime) {
		this.loggedInTime = loggedInTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logged_out_time", length = 0)
	public Date getLoggedOutTime() {
		return this.loggedOutTime;
	}

	public void setLoggedOutTime(Date loggedOutTime) {
		this.loggedOutTime = loggedOutTime;
	}

	@Column(name = "ip", length = 50)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "is_logged_in")
	public Integer getIsLoggedIn() {
		return this.isLoggedIn;
	}

	public void setIsLoggedIn(Integer isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}

	@Column(name = "device_details", length = 1000)
	public String getDeviceDetails() {
		return this.deviceDetails;
	}

	public void setDeviceDetails(String deviceDetails) {
		this.deviceDetails = deviceDetails;
	}

}
