package com.dq.arq.sme.domain;
// default package
// Generated Oct 6, 2016 4:54:51 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "arq_sme")
public class UserRoleDo implements java.io.Serializable {

	/**
	 * 
	 */
	public enum Role{
		ROLE_ADMIN,ROLE_USER,ROLE_REPORT;
	}
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Role role;

	public UserRoleDo() {
	}

	public UserRoleDo(String role) {
		this.role = Role.valueOf(role);
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "role", nullable = false, length = 50)
	public String getRole() {
		return this.role.name();
	}

	public void setRole(String role) {
		this.role = Role.valueOf(role);
	}


}
