package com.dq.arq.sme.domain;
// default package
// Generated Feb 13, 2017 12:02:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRoleMapDo generated by hbm2java
 */
@Entity
@Table(name = "user_role_map", catalog = "arq_sme")
public class UserRoleMapDo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private UserDo userDo;
	private UserRoleDo userRoleDo;

	public UserRoleMapDo() {
	}

	public UserRoleMapDo(UserDo userDo, UserRoleDo userRoleDo) {
		this.userDo = userDo;
		this.userRoleDo = userRoleDo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDo getUserDo() {
		return this.userDo;
	}

	public void setUserDo(UserDo userDo) {
		this.userDo = userDo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_role_id", nullable = false)
	public UserRoleDo getUserRoleDo() {
		return this.userRoleDo;
	}

	public void setUserRoleDo(UserRoleDo userRoleDo) {
		this.userRoleDo = userRoleDo;
	}

}
